<a href="https://colab.research.google.com/github/Chaeyeoncho/data_analysis_/blob/main/__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
file_path = '/content/데분.csv'

In [ ]:
data = pd.read_csv(file_path, encoding='ISO-8859-1')
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,25-Sep-21,2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-Sep-21,2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,24-Sep-21,2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,24-Sep-21,2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-Sep-21,2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 국가, 장르 별 전처리

In [ ]:
import pandas as pd

# CSV 파일 불러오기
file_path = '/content/데분.csv'
data = pd.read_csv(file_path , encoding='cp949')  # 한글 데이터를 포함하고 있으므로 'cp949' 인코딩 사용

# 필요한 컬럼만 선택
data_filtered = data[['country', 'listed_in']].dropna()

# 결측치 처리
data_filtered['country'].fillna('Unknown', inplace=True)  # 결측치를 'Unknown'으로 대체
data_filtered['listed_in'].fillna('No Category', inplace=True)  # 결측치를 'No Category'로 대체

# 'listed_in' 컬럼에서 카테고리를 쉼표로 구분하여 처리
data_filtered['listed_in'] = data_filtered['listed_in'].str.split(', ')
data_exploded = data_filtered.explode('listed_in')

# 중복 데이터 제거
data_exploded.drop_duplicates(inplace=True)

# 결과 확인
print(data_exploded.head())
print(data_exploded['listed_in'].unique())  # 카테고리 확인

# CSV 파일로 저장할 경우
#data_exploded.to_csv('/path/to/your/output_file.csv', index=False)

              country                                          listed_in
0   December 23, 2018                  Hailing from the mountains of Iga
0   December 23, 2018  Kanzo Hattori moves in with elementary school ...
1   , France, Algeria                                             Dramas
1   , France, Algeria                                 Independent Movies
1   , France, Algeria                               International Movies
['Hailing from the mountains of Iga'
 'Kanzo Hattori moves in with elementary school student Kenichi Mitsuba and his family to hone his skills as a ninja.'
 'Dramas' 'Independent Movies' 'International Movies'
 'International TV Shows' 'TV Dramas'
 'Nikki Glaser bares all in a blistering stand-up special about sex'
 "sobriety and getting over her own insecurities. And she won't spare you the details."
 'Singer-songwriter Gen Hoshino takes the stage at the sold out Tokyo Dome in his highly anticipated 2019 Pop Virus dome tour.'
 'After people in his town start turning up dead'
 'a grumpy landlord is visited by a man who recounts an unsolved serial murder case from 30 years ago.'
 'Action & Adventure' 'Comedies' 'Horror Movies'
 'Children & Family Movies' 'Music & Musicals' 'Classic & Cult TV'
 'Crime TV Shows' 'Cult Movies' 'Romantic Movies' 'Docuseries'
 'Spanish-Language TV Shows' 'Documentaries' 'Sports Movies'
 'LGBTQ Movies' 'Sci-Fi & Fantasy' 'Thrillers' 'Reality TV'
 'Romantic TV Shows' 'TV Comedies' 'TV Horror' "Kids' TV" 'Teen TV Shows'
 'Stand-Up Comedy' 'Classic Movies' 'British TV Shows'
 'Science & Nature TV' 'TV Mysteries' 'TV Thrillers' 'Movies'
 'TV Action & Adventure' 'TV Sci-Fi & Fantasy' 'Faith & Spirituality'
 'Stand-Up Comedy & Talk Shows' 'Korean TV Shows' 'Anime Features'
 'Anime Series' 'TV Shows' 'Sci-fi' 'Horror' 'Action' 'Drama' 'Romance'
 'Thriller']

# 국가별 인기 장르 집계

In [ ]:
import pandas as pd

# 파일 경로
file_path = '/content/데분.csv'

# 파일 불러오기 (ISO-8859-1 인코딩 사용)
data = pd.read_csv(file_path, encoding='ISO-8859-1')

# 관련 컬럼 선택 및 결측치 제거
filtered_data = data[['country', 'listed_in']].dropna()

# 국가별로 데이터 분리 (국가명이 여러 개인 경우 분리)
filtered_data['country'] = filtered_data['country'].apply(lambda x: [country.strip() for country in x.split(',')])
filtered_data = filtered_data.explode('country')

# 장르별로 데이터 분리 (여러 장르가 한 셀에 있는 경우 분리)
filtered_data['listed_in'] = filtered_data['listed_in'].apply(lambda x: [genre.strip() for genre in x.split(',')])
filtered_data = filtered_data.explode('listed_in')

# 유효한 국가 이름만 필터링 (영문자 및 공백만 포함된 문자열)
valid_countries = filtered_data['country'].str.contains('^[A-Za-z ]+$')
filtered_valid_countries = filtered_data[valid_countries]

# 각 국가별로 가장 인기 있는 장르 집계
popular_genre_by_country = filtered_valid_countries.groupby('country')['listed_in'].agg(
    lambda x: x.value_counts().idxmax())

# 결과 출력
print(popular_genre_by_country.head(20))

country
Afghanistan              Documentaries
Albania                         Dramas
Algeria                         Dramas
Angola              Action & Adventure
Argentina         International Movies
Armenia                  Documentaries
Australia                       Dramas
Austria           International Movies
Azerbaijan      International TV Shows
Bahamas             Action & Adventure
Bangladesh                      Dramas
Belarus               British TV Shows
Belgium           International Movies
Bermuda                  Documentaries
Botswana                 Documentaries
Brazil            International Movies
Bulgaria            Action & Adventure
Burkina Faso                    Dramas
Cambodia                        Dramas
Cameroon                        Dramas
Name: listed_in, dtype: object

#국가별 장르 선호 빈도수 분석

In [ ]:
import pandas as pd

# CSV 파일 불러오기
data_path = '/content/데분.csv'
data = pd.read_csv(data_path, encoding='cp949')  # 인코딩을 'cp949'로 설정

# 'country'와 'listed_in' 컬럼에 집중
data_filtered = data[['country', 'listed_in']].dropna()

# 'country' 컬럼 정제하기
data_filtered['country'] = data_filtered['country'].str.split(', ')
data_exploded_countries = data_filtered.explode('country')
data_exploded_countries['country'] = data_exploded_countries['country'].str.strip()
valid_countries = data_exploded_countries['country'].str.contains('^[a-zA-Z ]+$')
cleaned_data = data_exploded_countries[valid_countries]

# 'listed_in' 컬럼 처리하기
cleaned_data['listed_in'] = cleaned_data['listed_in'].str.split(', ')
cleaned_data_exploded = cleaned_data.explode('listed_in')

# 국가별로 'listed_in' 카테고리 빈도수 계산
country_genre_counts = cleaned_data_exploded.groupby(['country', 'listed_in']).size().unstack(fill_value=0)

# 결과 출력
print(country_genre_counts.head())  # 처음 몇 줄만 출력

listed_in    Action  Action & Adventure  Anime Features  Anime Series  \
country
Afghanistan       0                   0               0             0
Albania           0                   0               0             0
Algeria           0                   0               0             0
Angola            0                   1               0             0
Argentina         0                   3               0             0

listed_in    British TV Shows  Children & Family Movies  Classic & Cult TV  \
country
Afghanistan                 0                         0                  0
Albania                     0                         0                  0
Algeria                     0                         0                  0
Angola                      0                         0                  0
Argentina                   0                         3                  1

listed_in    Classic Movies  Comedies  Crime TV Shows  ...  TV Comedies  \
country                                                ...
Afghanistan               0         0               0  ...            0
Albania                   0         0               0  ...            0
Algeria                   1         0               0  ...            0
Angola                    0         0               0  ...            0
Argentina                 1        12               3  ...            1

listed_in    TV Dramas  TV Horror  TV Mysteries  TV Sci-Fi & Fantasy  \
country
Afghanistan          0          0             0                    0
Albania              0          0             0                    0
Algeria              0          0             0                    0
Angola               0          0             0                    0
Argentina            2          1             0                    0

listed_in    TV Shows  TV Thrillers  Teen TV Shows  Thriller  Thrillers
country
Afghanistan         0             0              0         0          0
Albania             0             0              0         0          0
Algeria             0             0              0         0          0
Angola              0             0              0         0          0
Argentina           0             0              1         0          6

[5 rows x 48 columns]

<ipython-input-21-741570f14d57>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['listed_in'] = cleaned_data['listed_in'].str.split(', ')

#gdp, 장르, 국가 병합

In [ ]:
import pandas as pd

# 파일 경로
content_data_path = '/content/데분.csv'
gdp_data_path = '/content/나라별gdp.csv'

# CSV 파일 불러오기
content_data = pd.read_csv(content_data_path, encoding='cp949')
gdp_data = pd.read_csv(gdp_data_path, encoding='cp949')

# 필요한 컬럼 선택 및 결측치 제거
content_filtered = content_data[['country', 'listed_in']].dropna()
gdp_filtered = gdp_data.rename(columns={'Country': 'country', 'GDP 2022': 'gdp'}).dropna()

# 'listed_in' 컬럼의 데이터를 쉼표로 분할
content_filtered['listed_in'] = content_filtered['listed_in'].str.split(', ')
content_exploded = content_filtered.explode('listed_in')

# 두 데이터셋 병합
merged_data = pd.merge(content_exploded, gdp_filtered, on='country', how='left')

# 결과 출력
print(merged_data.head())
print(merged_data.info())

# 병합된 데이터를 CSV 파일로 저장
#merged_data.to_csv('/path/to/your/merged_output.csv', index=False)

              country                                          listed_in  gdp
0   December 23, 2018                  Hailing from the mountains of Iga  NaN
1   December 23, 2018  Kanzo Hattori moves in with elementary school ...  NaN
2   , France, Algeria                                             Dramas  NaN
3   , France, Algeria                                 Independent Movies  NaN
4   , France, Algeria                               International Movies  NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6390 entries, 0 to 6389
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    6390 non-null   object
 1   listed_in  6390 non-null   object
 2   gdp        3361 non-null   float64
dtypes: float64(1), object(2)
memory usage: 149.9+ KB
None